version: "3"

services:
  # nginx reverse proxy
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

  # reverse proxy let's encrypt companion
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=w2w.space@domainsbyproxy.com

  # Remix fullstack application
  remix:
    image: remix
    container_name: remix
    restart: always
    environment:
      - VIRTUAL_HOST=${w2w.space}
      - LETSENCRYPT_HOST=${w2w.space}
      - LETSENCRYPT_EMAIL=w2w.space@domainsbyproxy.com
    depends_on:
      - redis

  # Redis database
  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data:
