export const fileIconMap: Record<string, string> = {
  default: "fas fa-file",
  "application/pdf": "fas fa-file-pdf",
  "application/zip": "fas fa-file-archive",
  "video/mp4": "fas fa-file-video",
  "image/jpeg": "fas fa-file-image",
  "image/png": "fas fa-file-image",
  "text/plain": "fas fa-file-alt",
  "application/x-zip-compressed": "fas fa-file-archive",
  "application/msword": "fas fa-file-word",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
    "fas fa-file-word",
  "application/vnd.ms-excel": "fas fa-file-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":
    "fas fa-file-excel",
  "application/vnd.ms-powerpoint": "fas fa-file-powerpoint",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation":
    "fas fa-file-powerpoint",
  "text/html": "fas fa-file-code",
  "application/json": "fas fa-file-code",
  "application/javascript": "fas fa-file-code",
  "text/css": "fas fa-file-code",
  "image/gif": "fas fa-file-image",
  "image/svg+xml": "fas fa-file-image",
  "audio/mpeg": "fas fa-file-audio",
  "audio/wav": "fas fa-file-audio",
  "video/x-msvideo": "fas fa-file-video",
  "video/quicktime": "fas fa-file-video",
  "application/x-rar-compressed": "fas fa-file-archive",
  "application/x-tar": "fas fa-file-archive",
  "application/rtf": "fas fa-file-alt",
  "application/vnd.oasis.opendocument.text": "fas fa-file-alt",
  "application/vnd.oasis.opendocument.spreadsheet": "fas fa-file-excel",
  "application/vnd.oasis.opendocument.presentation": "fas fa-file-powerpoint",
  "application/vnd.apple.pages": "fas fa-file-alt",
  "application/vnd.apple.numbers": "fas fa-file-excel",
  "application/vnd.apple.keynote": "fas fa-file-powerpoint",
};
